services:
  app:
    build: .
    container_name: backend-template
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/template
      ACCESS_TOKEN: ACCESS_TOKEN
      REFRESH_TOKEN: REFRESH_TOKEN
      REDIS_URL: http://redis:6379
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: miniopassword
      S3_BUCKET_NAME: default
      S3_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push && npm run start:prod"

  postgres:
    container_name: postgres-template
    image: postgres:17-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-template
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword
    command: server --console-address ":9001" /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      sh -c "mc alias set local http://minio:9000 minio miniopassword &&
             mc mb local/default || true"
    restart: on-failure

volumes:
  postgres_data:
  minio_data:
